[package]
name = "saunders-dev-lp"
version = "0.1.0"
edition = "2021"

[dependencies]
console_error_panic_hook = "0.1.7"
leptos = { version = "0.6.14", features = ["csr", "nightly"] }
stylers = "0.3.2"


[build-dependencies]
stylers = "0.3.2"